Format scripts using shfmt shfmt -l -w *
Signed-off-by: infinity-plus <navdhareharsh2001@gmail.ccom>

diff --git a/telegram b/telegram
--- a/telegram
+++ b/telegram
@@ -22,8 +22,7 @@ CURL_OPTIONS="-s"
 HAS_JQ=false
 hash jq >/dev/null 2>&1 && HAS_JQ=true
 
-
-function help {
+function help() {
 	version
 	echo "Usage: $0 [options] [message]"
 	echo
@@ -63,14 +62,14 @@ function help {
 	exit
 }
 
-function version {
+function version() {
 	echo "telegram.sh version $VERSION"
 	echo "by Fabian Schlenz"
 }
 
-function list_chats {
+function list_chats() {
 	log "$URL$TOKEN"
-	response=`curl $CURL_OPTIONS $URL$TOKEN/getUpdates`
+	response=$(curl $CURL_OPTIONS $URL$TOKEN/getUpdates)
 	log "$response"
 
 	if [ "$HAS_JQ" = true ]; then
@@ -78,7 +77,7 @@ function list_chats {
 		echo "If there are no chats or the chat you are looking for isn't there, run this command again"
 		echo "after sending a message to your bot via telegram."
 		echo
-		jq -r '.result | .[].message.chat | "\(.id|tostring) - \(.first_name) \(.last_name) (@\(.username))"' 2>/dev/null <<< "$response" || {
+		jq -r '.result | .[].message.chat | "\(.id|tostring) - \(.first_name) \(.last_name) (@\(.username))"' 2>/dev/null <<<"$response" || {
 			echo "Could not parse reponse from Telegram."
 			echo "Response was: $response"
 			exit 1
@@ -98,13 +97,13 @@ function list_chats {
 	fi
 }
 
-function receive_file {
+function receive_file() {
 	if [ "$HAS_JQ" = false ]; then
 		echo "You need to have jq installed in order to be able to download files."
 		exit 1
 	fi
 
-	result=`curl $CURL_OPTIONS $URL$TOKEN/getUpdates?allowed_updates=message`
+	result=$(curl $CURL_OPTIONS $URL$TOKEN/getUpdates?allowed_updates=message)
 	log "$result"
 	# {"ok":true,"result":[
 	#   {
@@ -115,24 +114,24 @@ function receive_file {
 	#       "chat":{"id":15773,"first_name":"Fabian","last_name":"Schlenz","username":"fabianonline","type":"private"},
 	#       "date":1526564127,
 	#       "document":{"file_name":"desktop.ini","file_id":"BQAav-HkXugI","file_size":282}}}]}
-	file_id=`jq -r '.result[-1].message.document.file_id' <<< "$result"`
+	file_id=$(jq -r '.result[-1].message.document.file_id' <<<"$result")
 	log "file_id: $file_id"
 	if [ "$file_id" == "null" ]; then
 		echo "Last message received apparently didn't contain a file. Aborting."
 		exit 1
 	fi
-	file_name=`jq -r '.result[-1].message.document.file_name' <<< "$result"`
+	file_name=$(jq -r '.result[-1].message.document.file_name' <<<"$result")
 	log "file_name: $file_name"
-	result=`curl $CURL_OPTIONS $URL$TOKEN/getFile?file_id=$file_id`
+	result=$(curl $CURL_OPTIONS $URL$TOKEN/getFile?file_id=$file_id)
 	log $result
 	# {"ok":true,"result":{"file_id":"BQAav-HkXugI","file_size":282,"file_path":"documents/file_271.ini"}}
-	path=`jq -r '.result.file_path' <<< "$result"`
+	path=$(jq -r '.result.file_path' <<<"$result")
 	log "path: $path"
 	if [ "$path" == "null" ]; then
 		echo "Could not parse telegram's response to getFile. Aborting."
 		exit 1
 	fi
-	file_name="`date +%s`_$file_name"
+	file_name="$(date +%s)_$file_name"
 	log "file_name: $file_name"
 	if [ -e "$file_name" ]; then
 		echo "File $file_name already exists. This is unexpected, so I'm quitting now."
@@ -142,24 +141,24 @@ function receive_file {
 	echo "File downloaded as $file_name"
 }
 
-function log {
+function log() {
 	[ "$DEBUG" = true ] && echo "DEBUG: $1"
 }
 
-function check_file {
+function check_file() {
 	if [ ! -e "$1" ]; then
 		echo "The file $1 does not exist."
 		exit 1
 	fi
 
 	size=$(stat -c%s "$1")
-	if (( size > 52428800 )); then
+	if ((size > 52428800)); then
 		echo "File $1 is breaking the file size limit imposed on Telegram bots (currently 50MB)."
 		exit 1
 	fi
 }
 
-function escapeMarkdown {
+function escapeMarkdown() {
 	res="${1//\*/∗}"
 	res="${res//_/＿}"
 	res="${res//\`/‵}"
@@ -169,64 +168,64 @@ function escapeMarkdown {
 
 while getopts "t:c:i:f:MHCrhlvjnRDN" opt; do
 	case $opt in
-		t)
-			TOKEN="$OPTARG"
-			;;
-		c)
-			CHATS+=("$OPTARG")
-			;;
-		i)
-			IMAGE_FILE="$OPTARG"
-			;;
-		f)
-			DOCUMENT_FILE="$OPTARG"
-			;;
-		M)
-			PARSE_MODE="Markdown"
-			;;
-		H)
-			PARSE_MODE="HTML"
-			;;
-		C)
-			PARSE_MODE="Markdown"
-			CODE_MODE=1
-			;;
-		r)
-			PARSE_MODE="Markdown"
-			CRON_MODE=1
-			;;
-		l)
-			ACTION="list_chats"
-			;;
-		v)
-			DEBUG=true
-			;;
-		j)
-			HAS_JQ=false
-			;;
-		n)
-			DRY_RUN=true
-			;;
-		R)
-			ACTION="receive_file"
-			;;
-		D)
-			DISABLE_WEB_PAGE_PREVIEW=true
-			;;
-		N)
-			DISABLE_NOTIFICATION=true
-			;;
-		?|h)
-			help
-			;;
-		:)
-			echo "Option -$OPTARG needs an argument."
-			exit 1
-			;;
-		\?)
-			echo "Invalid option -$OPTARG"
-			exit 1
-			;;
+	t)
+		TOKEN="$OPTARG"
+		;;
+	c)
+		CHATS+=("$OPTARG")
+		;;
+	i)
+		IMAGE_FILE="$OPTARG"
+		;;
+	f)
+		DOCUMENT_FILE="$OPTARG"
+		;;
+	M)
+		PARSE_MODE="Markdown"
+		;;
+	H)
+		PARSE_MODE="HTML"
+		;;
+	C)
+		PARSE_MODE="Markdown"
+		CODE_MODE=1
+		;;
+	r)
+		PARSE_MODE="Markdown"
+		CRON_MODE=1
+		;;
+	l)
+		ACTION="list_chats"
+		;;
+	v)
+		DEBUG=true
+		;;
+	j)
+		HAS_JQ=false
+		;;
+	n)
+		DRY_RUN=true
+		;;
+	R)
+		ACTION="receive_file"
+		;;
+	D)
+		DISABLE_WEB_PAGE_PREVIEW=true
+		;;
+	N)
+		DISABLE_NOTIFICATION=true
+		;;
+	? | h)
+		help
+		;;
+	:)
+		echo "Option -$OPTARG needs an argument."
+		exit 1
+		;;
+	\?)
+		echo "Invalid option -$OPTARG"
+		exit 1
+		;;
 	esac
 done
 
@@ -297,7 +296,7 @@ if [ $CRON_MODE -eq 1 ]; then
 		if [ "${line:0:2}" = "+ " ]; then
 			ONLY_COMMANDS=0
 		fi
-	done <<< "$TEXT"
+	done <<<"$TEXT"
 
 	if [ "$ONLY_COMMANDS" -eq 1 ]; then
 		exit 0
@@ -368,7 +367,7 @@ for id in "${CHATS[@]}"; do
 		status=0
 		response='{"ok": true}'
 	else
-		response=`curl $MY_CURL_OPTIONS <<< "$TEXT"`
+		response=$(curl $MY_CURL_OPTIONS <<<"$TEXT")
 		status=$?
 	fi
 	log "Response was: $response"
@@ -380,9 +379,9 @@ for id in "${CHATS[@]}"; do
 	fi
 
 	if [ "$HAS_JQ" = true ]; then
-		if [ "`jq -r '.ok' <<< "$response"`" != "true" ]; then
+		if [ "$(jq -r '.ok' <<<"$response")" != "true" ]; then
 			echo "Telegram reported following error:"
-			jq -r '"\(.error_code): \(.description)"' <<< "$response"
+			jq -r '"\(.error_code): \(.description)"' <<<"$response"
 			echo "Quitting."
 			exit 1
 		fi
